// Pinned snippets for docs/concepts/unions-literals-enums.md.
import { describe, it, expect, expectTypeOf } from 'vitest'
import { Sapphire, type Infer } from '@ascendance-hub/sapphire-core'

const a = new Sapphire()

describe('docs/concepts/unions-literals-enums.md — snippet pinning', () => {
  it('union — string | number', () => {
    // --- snippet: union ---
    const id = a.type().union([a.string(), a.number()])
    type Id = Infer<typeof id>
    // Id = string | number
    // --- end snippet ---

    expectTypeOf<Id>().toEqualTypeOf<string | number>()
    expect(id.parse('u1')).toBe('u1')
    expect(id.parse(42)).toBe(42)
    expect(id.safeParse(true).success).toBe(false)
  })

  it('literal — narrowed single value', () => {
    // --- snippet: literal ---
    const kind = a.type().literal('admin')
    type Kind = Infer<typeof kind>
    // Kind = 'admin'
    // --- end snippet ---

    expectTypeOf<Kind>().toEqualTypeOf<'admin'>()
    expect(kind.parse('admin')).toBe('admin')
    expect(kind.safeParse('user').success).toBe(false)
  })

  it('enum from const tuple — narrowed union', () => {
    // --- snippet: enum from tuple ---
    const role = a.type().enum(['admin', 'editor', 'viewer'] as const)
    type Role = Infer<typeof role>
    // Role = 'admin' | 'editor' | 'viewer'
    // --- end snippet ---

    expectTypeOf<Role>().toEqualTypeOf<'admin' | 'editor' | 'viewer'>()
    expect(role.parse('editor')).toBe('editor')
    expect(role.safeParse('owner').success).toBe(false)
  })

  it('enum from a TS enum — numeric reverse mappings are filtered', () => {
    // --- snippet: enum from TS enum ---
    enum Status {
      Active = 1,
      Inactive = 2,
    }
    const status = a.type().enum(Status)
    // _output is Status (a numeric union); reverse mappings ('1','2' → name)
    // generated by TS are filtered before being baked into the IR.
    // --- end snippet ---

    expect(status.parse(1)).toBe(1)
    expect(status.parse(2)).toBe(2)
    expect(status.safeParse(3).success).toBe(false)
    // The reverse mappings should NOT be valid values:
    expect(status.safeParse('Active').success).toBe(false)
  })
})
